name: surf_practice_chat_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  surf_study_jam: ^0.1.0+1
  cupertino_icons: ^1.0.5

  equatable: ^2.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  intl: ^0.17.0
  map_launcher: ^2.3.0+1
  geolocator: ^9.0.1
  image_picker: ^0.8.5+3
  bubble: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:

  uses-material-design: true
